// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB66Qdfdh8AOSJ94e4DAqySR5-k5aG4sos',
    appId: '1:1087817286203:android:7d3a73d7b12de9434b921e',
    messagingSenderId: '1087817286203',
    projectId: 'fireship-lessons-8ac7d',
    storageBucket: 'fireship-lessons-8ac7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpTDfdmFi1WHmiwEC5t_IAuh5nt5LBrs0',
    appId: '1:1087817286203:ios:269e8e9766f5b88f4b921e',
    messagingSenderId: '1087817286203',
    projectId: 'fireship-lessons-8ac7d',
    storageBucket: 'fireship-lessons-8ac7d.appspot.com',
    androidClientId: '1087817286203-4a2f77nfb4blb0iqnj5bo0gncl8r78tq.apps.googleusercontent.com',
    iosClientId: '1087817286203-b531tcqlkftu9scfoo3dtlj1tqtbsmsg.apps.googleusercontent.com',
    iosBundleId: 'io.github.kakimnsnv.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpTDfdmFi1WHmiwEC5t_IAuh5nt5LBrs0',
    appId: '1:1087817286203:ios:c1a2f88b73ac8b584b921e',
    messagingSenderId: '1087817286203',
    projectId: 'fireship-lessons-8ac7d',
    storageBucket: 'fireship-lessons-8ac7d.appspot.com',
    androidClientId: '1087817286203-4a2f77nfb4blb0iqnj5bo0gncl8r78tq.apps.googleusercontent.com',
    iosClientId: '1087817286203-f55gk9r452su0vc45tttnvpu1m9b3c4k.apps.googleusercontent.com',
    iosBundleId: 'io.github.kakimnsnv.myapp.RunnerTests',
  );
}
